# Generated by Django 4.2.4 on 2023-08-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('discord', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('platform', models.CharField(choices=[('W', 'Windows'), ('M', 'MacOS'), ('L', 'Linux'), ('X', 'XBOX'), ('P', 'Playstation'), ('S', 'Switch'), ('I', 'iOS'), ('A', 'Android')], max_length=1)),
            ],
        ),
    ]
