# Generated by Django 4.2.4 on 2023-08-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('date_created', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('discord', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('platform', models.CharField(choices=[('J', 'Java Edition'), ('B', 'Bedrock Edition')], max_length=1)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
