# Generated by Django 4.2.2 on 2023-08-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='accepted',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='status',
            field=models.CharField(default='Applied', max_length=15),
        ),
    ]
