# Generated by Django 4.2.2 on 2023-08-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_remove_userrequest_accepted_userrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
